apiVersion: v1
kind: Service
metadata:
  labels:
    app: asm
  name: asm
  namespace: {{NAMESPACE}}
spec:
  ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: asm
  type: ClusterIP
