apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: asm
  name: asm
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: asm
    spec:
      containers:
        - image: {{IMAGE}}
          imagePullPolicy: IfNotPresent
          name: asm
          ports:
            - containerPort: 80
              protocol: TCP
