apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  labels:
    app: asm
  name: asm
  namespace: asm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: asm
    spec:
      containers:
        image: {{ASM-IMAGE}}
        imagePullPolicy: IfNotPresent
        name: asm-api
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asm
  namespace: asm
spec:
  ingressClassName: nginx
  rules:
  - host: asm.synsense.ai
    http:
      paths:
      - backend:
          service:
            name: asm
            port:
              number: 80
        path: /
        pathType: Prefix

