apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asm
  namespace: asm
spec:
  ingressClassName: nginx
  rules:
  - host: asm.synsense.ai
    http:
      paths:
      - backend:
          service:
            name: asm
            port:
              number: 80
        path: /
        pathType: Prefix

