apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  labels:
    app: eladmin
  name: eladmin
  namespace: eladmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eladmin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eladmin
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: db
        - name: DB_USER
          value: root
        - name: DB_PWD
          value: Admin@123.
        - name: REDIS_HOST
          value: redis
        image: {{ELADMIN-IMAGE}}
        imagePullPolicy: IfNotPresent
        name: eladmin-api
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
